# Generated by Django 5.1.5 on 2025-07-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_answer_status_answer_termination_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="choices",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
